#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Nov 23 14:07:11 +08 2023
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim mcs_top_vanilla_behav -key {Behavioral:sim_1:Functional:mcs_top_vanilla} -tclbatch mcs_top_vanilla.tcl -protoinst "protoinst_files/bd_3914.protoinst" -log simulate.log"
xsim mcs_top_vanilla_behav -key {Behavioral:sim_1:Functional:mcs_top_vanilla} -tclbatch mcs_top_vanilla.tcl -protoinst "protoinst_files/bd_3914.protoinst" -log simulate.log

